import { CSSProperties } from "react";

export const vibeCodingStyles = {
  root: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "8px",
    height: "507px",
    justifyContent: "flex-start",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "800px",
  } as CSSProperties,
  mainContainer: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  imageSection: {
    backgroundColor: "var(--color-text-secondary)",
    borderBottomLeftRadius: "16px",
    borderBottomRightRadius: "16px",
    borderTopLeftRadius: "40px",
    borderTopRightRadius: "300px",
    flex: "1 0 0px",
    height: "1px",
    overflow: "hidden",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  imageInner: {
    backgroundColor: "var(--color-bg-secondary)",
    borderBottomLeftRadius: "40px",
    borderBottomRightRadius: "40px",
    borderTopLeftRadius: "40px",
    borderTopRightRadius: "40px",
    WebkitUserSelect: "none",
    flex: "none",
    height: "100%",
    left: "0px",
    overflow: "hidden",
    position: "absolute",
    top: "0px",
    userSelect: "none",
    width: "100%",
  } as CSSProperties,
  mainImage: {
    flex: "none",
    height: "100%",
    left: "0px",
    overflow: "hidden",
    position: "absolute",
    top: "0px",
    width: "100%",
    objectFit: "cover",
    objectPosition: "center center",
  } as CSSProperties,
  textRow: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    height: "min-content",
    justifyContent: "space-between",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  title: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "22px",
    fontStyle: "normal",
    fontWeight: 400,
    letterSpacing: "0em",
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-muted)",
    textDecoration: "none",
    textTransform: "none",
    margin: 0,
  } as CSSProperties,
  subtitle: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 400,
    letterSpacing: "0em",
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-disabled)",
    textDecoration: "none",
    textTransform: "none",
    margin: 0,
  } as CSSProperties,
};
