import { CSSProperties } from "react";

export const appAnniversaryStyles = {
  root: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "8px",
    height: "506px",
    justifyContent: "flex-start",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "800px",
    textDecoration: "none",
  } as CSSProperties,
  mainContent: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  imageContainerOuter: {
    flex: "1 0 0px",
    height: "1px",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    backgroundColor: "var(--color-text-secondary)",
    borderBottomLeftRadius: "300px",
    borderBottomRightRadius: "40px",
    borderTopLeftRadius: "200px",
    borderTopRightRadius: "300px",
  } as CSSProperties,
  imageContainerInner: {
    flex: "none",
    height: "100%",
    left: "0px",
    overflow: "hidden",
    position: "absolute",
    top: "0px",
    userSelect: "none",
    width: "100%",
    backgroundColor: "var(--color-bg-secondary)",
  } as CSSProperties,
  image: {
    display: "block",
    width: "100%",
    height: "100%",
    objectFit: "fill",
    objectPosition: "center",
  } as CSSProperties,
  textRow: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "min-content",
    justifyContent: "flex-start",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  title: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "22px",
    fontWeight: 400,
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-muted)",
    margin: 0,
  } as CSSProperties,
  subtitle: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "12px",
    fontWeight: 400,
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-disabled)",
    margin: 0,
    letterSpacing: "0em",
  } as CSSProperties,
};
