import { CSSProperties } from "react";

export const braceletStyles = {
  root: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "8px",
    height: "507px",
    justifyContent: "flex-start",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "800px",
    textDecoration: "none",
    cursor: "pointer",
  } as CSSProperties,
  mainContent: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  imageContainerOuter: {
    flex: "1 0 0px",
    height: "1px",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    backgroundColor: "var(--color-text-secondary)", // Fallback
    borderRadius: "300px",
  } as CSSProperties,
  imageContainerInner: {
    flex: "none",
    height: "100%",
    left: "0px",
    overflow: "hidden",
    position: "absolute",
    top: "0px",
    userSelect: "none",
    width: "100%",
    backgroundColor: "var(--color-bg-secondary, rgb(245, 245, 245))",
    borderRadius: "300px",
  } as CSSProperties,
  image: {
    display: "block",
    width: "100%",
    height: "100%",
    borderRadius: "inherit",
    objectFit: "cover",
    objectPosition: "center",
  } as CSSProperties,
  customShape: {
    aspectRatio: "2.888888888888889 / 1",
    bottom: "-1px",
    flex: "none",
    height: "auto", // Set to auto to respect width/aspect-ratio
    left: "50%",
    position: "absolute",
    width: "20%",
    transform: "translateX(-50%)",
    zIndex: 1,
    pointerEvents: "none",
  } as CSSProperties,
  circleButton: {
    aspectRatio: "1 / 1",
    bottom: "0px",
    flex: "none",
    height: "auto", // Set to auto to respect width/aspect-ratio
    left: "50%",
    overflow: "hidden",
    position: "absolute",
    width: "6%",
    transform: "translateX(-50%)",
    backgroundColor: "var(--color-static-black, rgb(0, 0, 0))",
    borderRadius: "999px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  } as CSSProperties,
  arrowIcon: {
    width: "28px",
    height: "28px",
    display: "block",
  } as CSSProperties,
  textRow: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    height: "min-content",
    justifyContent: "space-between",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  title: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "22px",
    fontWeight: 400,
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-muted)",
    margin: 0,
  } as CSSProperties,
  subtitle: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "12px",
    fontWeight: 400,
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-disabled)",
    margin: 0,
    letterSpacing: "0em",
  } as CSSProperties,
};
