import { CSSProperties } from "react";

export const googleIOStyles = {
  root: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "8px",
    height: "507px",
    justifyContent: "flex-start",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "800px",
  } as CSSProperties,
  mainContent: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  topRow: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: "9px",
    height: "32%",
    justifyContent: "center",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  videoCard: {
    alignContent: "center",
    alignItems: "center",
    aspectRatio: "1 / 1",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "162px",
    backgroundColor: "var(--color-bg-secondary, rgb(245, 245, 245))",
    borderRadius: "40px",
  } as CSSProperties,
  videoInner: {
    flex: "none",
    height: "100%",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    backgroundColor: "var(--color-bg-secondary, rgb(245, 245, 245))",
  } as CSSProperties,
  videoElement: {
    height: "100%",
    width: "100%",
    objectFit: "cover",
    display: "block",
  } as CSSProperties,
  imageCard: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "1 0 0px",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "1px", // Flex will expand it
    borderRadius: "40px",
  } as CSSProperties,
  topImage: {
    flex: "none",
    height: "100%",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    objectFit: "cover",
  } as CSSProperties,
  bottomCard: {
    flex: "1 0 0px",
    height: "1px",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    backgroundColor: "var(--color-text-secondary, rgb(85, 85, 85))",
    borderRadius: "40px 40px 0px 40px",
  } as CSSProperties,
  bottomCardInner: {
    flex: "none",
    height: "100%",
    left: "0px",
    overflow: "hidden",
    position: "absolute",
    top: "0px",
    width: "100%",
    backgroundColor: "var(--color-bg-secondary, rgb(245, 245, 245))",
  } as CSSProperties,
  awardBadge: {
    alignContent: "center",
    alignItems: "center",
    aspectRatio: "3.065 / 1",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: "10px",
    height: "32px",
    justifyContent: "center",
    left: "20px",
    overflow: "hidden",
    padding: "0px",
    position: "absolute",
    top: "20px",
    width: "12%",
    zIndex: 2,
    opacity: 0, // Matches source
  } as CSSProperties,
  mainImage: {
    flex: "none",
    height: "100%",
    left: "50%",
    top: "50%",
    transform: "translate(-50%, -50%)",
    overflow: "visible",
    position: "absolute",
    width: "100%",
    objectFit: "cover",
    zIndex: 1,
  } as CSSProperties,
  moonIconContainer: {
    aspectRatio: "1 / 1",
    bottom: "-1px",
    flex: "none",
    height: "96px",
    position: "absolute",
    right: "-1px",
    width: "12%",
    zIndex: 3,
  } as CSSProperties,
  moonIconSmallContainer: {
    aspectRatio: "1 / 1",
    bottom: "0px",
    flex: "none",
    height: "56px",
    overflow: "hidden",
    position: "absolute",
    right: "1px",
    width: "7%",
    backgroundColor: "var(--color-static-black, rgb(0, 0, 0))",
    borderRadius: "999px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 4,
  } as CSSProperties,
  textRow: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    height: "min-content",
    justifyContent: "space-between",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  title: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "22px",
    fontWeight: 400,
    letterSpacing: "0em",
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-muted, #999999)",
    margin: 0,
  } as CSSProperties,
  subtitle: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "12px",
    fontWeight: 400,
    letterSpacing: "0em",
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-disabled, #bbbbbb)",
    margin: 0,
  } as CSSProperties,
};
