import { CSSProperties } from "react";

export const jpShoeStyles = {
  root: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "8px",
    height: "507px",
    justifyContent: "flex-start",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "800px",
    textDecoration: "none",
    cursor: "pointer",
  } as CSSProperties,
  mainContent: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  videoContainerOuter: {
    flex: "1 0 0px",
    height: "1px",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    backgroundColor: "var(--color-text-secondary)", // Fallback color
    borderTopLeftRadius: "40px",
    borderTopRightRadius: "40px",
    borderBottomLeftRadius: "40px",
    borderBottomRightRadius: "0px",
    // Note: The original code had border radius 40px on the container
  } as CSSProperties,
  videoContainerInner: {
    flex: "none",
    height: "100%",
    left: "0px",
    overflow: "hidden",
    position: "absolute",
    top: "0px",
    userSelect: "none",
    width: "100%",
    borderTopLeftRadius: "40px",
    borderTopRightRadius: "40px",
    borderBottomLeftRadius: "40px",
    borderBottomRightRadius: "0px",
  } as CSSProperties,
  video: {
    display: "block",
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center",
    backgroundColor: "rgba(0, 0, 0, 0)",
  } as CSSProperties,
  cornerShape: {
    aspectRatio: "1 / 1",
    bottom: "-1px",
    flex: "none",
    height: "96px", // approx 12% of 800 is 96
    position: "absolute",
    right: "-1px",
    width: "12%",
    zIndex: 1,
    pointerEvents: "none",
  } as CSSProperties,
  circleButton: {
    aspectRatio: "1 / 1",
    bottom: "0px",
    flex: "none",
    height: "56px", // approx 7% of 800 is 56
    overflow: "hidden",
    position: "absolute",
    right: "1px",
    width: "7%",
    backgroundColor: "var(--color-static-black)",
    borderRadius: "999px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  } as CSSProperties,
  arrowIcon: {
    width: "28px",
    height: "28px",
    display: "block",
  } as CSSProperties,
  textRow: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    height: "min-content",
    justifyContent: "space-between",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  title: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "22px",
    fontWeight: 400,
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-muted)",
    margin: 0,
  } as CSSProperties,
  subtitle: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "12px",
    fontWeight: 400,
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-disabled)",
    margin: 0,
    letterSpacing: "0em",
  } as CSSProperties,
};
