import { CSSProperties } from "react";

export const melmoryCubeStyles = {
	root: {
		alignContent: "flex-start",
		alignItems: "flex-start",
		display: "flex",
		flexDirection: "column",
		flexWrap: "nowrap",
		gap: "8px",
		height: "507px",
		justifyContent: "flex-start",
		overflow: "visible",
		padding: "0px",
		position: "relative",
		width: "800px",
	} as CSSProperties,
	mainContainer: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  imageSection: {
    backgroundColor: "var(--color-text-secondary)",
    borderBottomLeftRadius: "16px",
    borderBottomRightRadius: "16px",
    borderTopLeftRadius: "40px",
    borderTopRightRadius: "300px",
    flex: "1 0 0px",
    height: "1px",
    overflow: "hidden",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  imageInner: {
    backgroundColor: "var(--color-bg-secondary)",
    borderBottomLeftRadius: "40px",
    borderBottomRightRadius: "40px",
    borderTopLeftRadius: "40px",
    borderTopRightRadius: "40px",
    WebkitUserSelect: "none",
    flex: "none",
    height: "100%",
    left: "0px",
    overflow: "hidden",
    position: "absolute",
    top: "0px",
    userSelect: "none",
    width: "100%",
  } as CSSProperties,
  awardBadge: {
    alignContent: "center",
    alignItems: "center",
    aspectRatio: "3.0652173913043477 / 1",
    bottom: "20px",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: "10px",
    height: "37px",
    justifyContent: "center",
    left: "20px",
    opacity: 0.3,
    overflow: "hidden",
    padding: "0px",
    position: "absolute",
    width: "112px",
  } as CSSProperties,
  mainImage: {
    flex: "none",
    height: "100%",
    left: "0px",
    overflow: "hidden",
    position: "absolute",
    top: "0px",
    width: "100%",
    objectFit: "cover",
    objectPosition: "center center",
  } as CSSProperties,
  iconContainer1: {
    aspectRatio: "1 / 1",
    bottom: "-1px",
    flex: "none",
    height: "96px",
    position: "absolute",
    right: "-1px",
    width: "12%",
    zIndex: 2,
  } as CSSProperties,
  iconContainer2: {
    aspectRatio: "1 / 1",
    backgroundColor: "var(--color-static-black)",
    borderBottomLeftRadius: "999px",
    borderBottomRightRadius: "999px",
    borderTopLeftRadius: "999px",
    borderTopRightRadius: "999px",
    bottom: "0px",
    flex: "none",
    height: "56px",
    overflow: "hidden",
    position: "absolute",
    right: "1px",
    width: "7%",
    zIndex: 3,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } as CSSProperties,
  textRow: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    height: "min-content",
    justifyContent: "space-between",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
	title: {
		fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
		fontSize: "22px",
		fontStyle: "normal",
		fontWeight: 400,
		letterSpacing: "0em",
		lineHeight: "1.2em",
		textAlign: "left",
		color: "var(--color-text-muted)",
		textDecoration: "none",
		textTransform: "none",
		margin: 0,
	} as CSSProperties,
	subtitle: {
		fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
		fontSize: "12px",
		fontStyle: "normal",
		fontWeight: 400,
		letterSpacing: "0em",
		lineHeight: "1.2em",
		textAlign: "left",
		color: "var(--color-text-disabled)",
		textDecoration: "none",
		textTransform: "none",
		margin: 0,
	} as CSSProperties,
};
