import { CSSProperties } from "react";

export const memberStyles = {
  root: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "8px",
    height: "505px",
    justifyContent: "flex-start",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "800px",
  } as CSSProperties,
  mainContainer: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  topRow: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: "9px",
    height: "32%",
    justifyContent: "center",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  leftCard: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "1 0 0px",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "1px",
    borderRadius: "40px",
  } as CSSProperties,
  leftCardImage: {
    flex: "none",
    height: "100%",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    objectFit: "cover",
  } as CSSProperties,
  rightCard: {
    alignContent: "center",
    alignItems: "center",
    aspectRatio: "1.323943661971831 / 1",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "auto",
    borderRadius: "40px",
    backgroundColor: "var(--color-bg-secondary)",
  } as CSSProperties,
  rightCardImage: {
    flex: "none",
    height: "100%",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    objectFit: "cover",
  } as CSSProperties,
  bottomCard: {
    flex: "1 0 0px",
    height: "1px",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    borderRadius: "40px",
    backgroundColor: "var(--color-text-secondary)",
  } as CSSProperties,
  bottomCardInner: {
    flex: "none",
    height: "100%",
    left: "0px",
    overflow: "hidden",
    position: "absolute",
    top: "0px",
    width: "100%",
    backgroundColor: "var(--color-bg-secondary)",
  } as CSSProperties,
  mainImage: {
    flex: "none",
    height: "100%",
    left: "50%",
    top: "50%",
    transform: "translate(-50%, -50%)",
    overflow: "visible",
    position: "absolute",
    width: "100%",
    objectFit: "cover",
  } as CSSProperties,
  textRow: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    height: "min-content",
    justifyContent: "space-between",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  title: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "22px",
    fontWeight: 400,
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-muted)",
    margin: 0,
  } as CSSProperties,
  subtitle: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "12px",
    fontWeight: 400,
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-disabled)",
    margin: 0,
  } as CSSProperties,
};
