import { CSSProperties } from "react";

export const nikeShoeFinderStyles = {
  root: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "8px",
    height: "507px",
    justifyContent: "flex-start",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "800px",
  } as CSSProperties,
  mainContainer: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  topRow: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: "9px",
    height: "32%",
    justifyContent: "center",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  largeImageContainer: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "1 0 0px",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "1px", // Flex will override
  } as CSSProperties,
  imageWrapper: {
    flex: "none",
    height: "100%",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    borderRadius: "40px",
  } as CSSProperties,
  smallImageContainer: {
    alignContent: "center",
    alignItems: "center",
    backgroundColor: "var(--color-bg-secondary, rgb(245, 245, 245))",
    borderRadius: "40px",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "32%",
  } as CSSProperties,
  gifImage: {
    flex: "none",
    height: "100%",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    borderRadius: "40px",
    objectFit: "cover",
  } as CSSProperties,
  middleRow: {
    backgroundColor: "var(--color-text-secondary, rgb(85, 85, 85))",
    borderBottomLeftRadius: "40px",
    borderTopLeftRadius: "40px",
    borderTopRightRadius: "40px",
    flex: "1 0 0px",
    height: "1px", // Flex will override
    overflow: "hidden",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  awardContainer: {
    backgroundColor: "var(--color-bg-secondary, rgb(245, 245, 245))",
    height: "100%",
    left: "0px",
    overflow: "hidden",
    position: "absolute",
    top: "0px",
    width: "100%",
  } as CSSProperties,
  awardBadge: {
    alignContent: "center",
    alignItems: "center",
    aspectRatio: "3.0652173913043477 / 1",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: "10px",
    height: "32px",
    justifyContent: "center",
    left: "20px",
    overflow: "hidden",
    padding: "0px",
    position: "absolute",
    top: "20px",
    width: "12%",
    opacity: 0, // Initial state
  } as CSSProperties,
  mainShoeImage: {
    flex: "none",
    height: "100%",
    left: "50%",
    overflow: "visible",
    position: "absolute",
    top: "50%",
    width: "100%",
    transform: "translate(-50%, -50%)",
    objectFit: "cover",
  } as CSSProperties,
  iconContainer1: {
    aspectRatio: "1 / 1",
    bottom: "-1px",
    flex: "none",
    height: "96px",
    position: "absolute",
    right: "-1px",
    width: "12%",
  } as CSSProperties,
  iconContainer2: {
    aspectRatio: "1 / 1",
    backgroundColor: "var(--color-static-black, rgb(0, 0, 0))",
    borderBottomLeftRadius: "999px",
    borderBottomRightRadius: "999px",
    borderTopLeftRadius: "999px",
    borderTopRightRadius: "999px",
    bottom: "0px",
    flex: "none",
    height: "56px",
    overflow: "hidden",
    position: "absolute",
    right: "1px",
    width: "7%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } as CSSProperties,
  textRow: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    height: "min-content",
    justifyContent: "space-between",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  title: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "22px",
    fontWeight: 400,
    letterSpacing: "0em",
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-muted, #999999)",
    margin: 0,
  } as CSSProperties,
  subtitle: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "12px",
    fontWeight: 400,
    letterSpacing: "0em",
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-disabled, #bbbbbb)",
    margin: 0,
  } as CSSProperties,
  link: {
    color: "var(--color-text-link, rgb(0, 153, 255))",
    textDecoration: "underline",
  } as CSSProperties,
};
