import { CSSProperties } from "react";

export const wildwoodStyles = {
  root: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "8px",
    height: "507px",
    justifyContent: "flex-start",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "800px",
  } as CSSProperties,
  mainContent: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: "10px",
    height: "100%",
    justifyContent: "center",
    overflow: "visible",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  imageSection: {
    flex: "1 0 0px",
    height: "1px", // Flex will override
    overflow: "hidden",
    position: "relative",
    width: "100%",
    backgroundColor: "var(--color-text-secondary, rgb(85, 85, 85))",
    borderBottomLeftRadius: "100px",
    borderBottomRightRadius: "16px",
    borderTopLeftRadius: "200px",
    borderTopRightRadius: "100px",
  } as CSSProperties,
  innerBackground: {
    height: "100%",
    left: "0px",
    overflow: "visible", // Original was visible, keeping it
    position: "absolute",
    top: "0px",
    width: "100%",
    backgroundColor: "var(--color-bg-secondary, rgb(245, 245, 245))",
    borderRadius: "40px",
  } as CSSProperties,
  awardBadge: {
    position: "absolute",
    top: "20px", // Approximate position based on NikeShoeFinder layout or defaults
    left: "20px",
    display: "flex",
    gap: "10px",
    opacity: 0, // Initial state
    zIndex: 2,
  } as CSSProperties,
  mainImage: {
    flex: "none",
    height: "100%",
    width: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    objectFit: "cover",
    borderRadius: "40px", // Matches innerBackground
    zIndex: 1,
  } as CSSProperties,
  iconContainer1: {
    aspectRatio: "1 / 1",
    bottom: "-1px",
    flex: "none",
    height: "96px",
    position: "absolute",
    right: "-1px",
    width: "12%", // Fallback
    zIndex: 3,
  } as CSSProperties,
  iconContainer2: {
    aspectRatio: "1 / 1",
    backgroundColor: "var(--color-static-black, rgb(0, 0, 0))",
    borderRadius: "999px",
    bottom: "0px",
    flex: "none",
    height: "56px",
    overflow: "hidden",
    position: "absolute",
    right: "1px",
    width: "7%", // Fallback
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 4,
  } as CSSProperties,
  textRow: {
    alignContent: "center",
    alignItems: "center",
    display: "flex",
    flex: "none",
    flexDirection: "row",
    flexWrap: "nowrap",
    height: "min-content",
    justifyContent: "space-between",
    overflow: "hidden",
    padding: "0px",
    position: "relative",
    width: "100%",
  } as CSSProperties,
  title: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "22px",
    fontWeight: 400,
    letterSpacing: "0em",
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-muted, #999999)",
    margin: 0,
  } as CSSProperties,
  subtitle: {
    fontFamily: '"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
    fontSize: "12px",
    fontWeight: 400,
    letterSpacing: "0em",
    lineHeight: "1.2em",
    textAlign: "left",
    color: "var(--color-text-disabled, #bbbbbb)",
    margin: 0,
  } as CSSProperties,
};
