// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 65748388c4c5aa05 "Portfolio", do not edit manually */
"use client";

// virtual:name
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/0bhW0TTKh4XjSweuSYai/ICy36dBj8p2fR6nCVc7B/kR3Tje3H6.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	ComponentViewportProvider,
	cx as cx2,
	getFonts,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/cA2Xr8CRaOKM7ZTv01SI/rDrporcPHtJzKbYpiFNA/m9xBAxWo9.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = [
	"SaB_4YMI7",
	"sz9N3g3MI",
	"a8ROf930s",
	"Vg2pKRqL3",
	"yA6K4aJk6",
];
var serializationHash = "framer-Rn9Mn";
var variantClassNames = {
	a8ROf930s: "framer-v-1fjkeyw",
	SaB_4YMI7: "framer-v-3xk79r",
	sz9N3g3MI: "framer-v-1is0smo",
	Vg2pKRqL3: "framer-v-opx3h",
	yA6K4aJk6: "framer-v-11ljp8c",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "SaB_4YMI7",
	"Variant 2": "sz9N3g3MI",
	"Variant 3": "a8ROf930s",
	"Variant 4": "Vg2pKRqL3",
	"Variant 5": "yA6K4aJk6",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "SaB_4YMI7",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "SaB_4YMI7",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear1tg5wz5 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("sz9N3g3MI"), 2e3);
	});
	const onAppearsy4wnq = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("a8ROf930s"), 2e3);
	});
	const onAppear27vrgn = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("Vg2pKRqL3"), 2e3);
	});
	const onAppear11o3rjk = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("yA6K4aJk6"), 2e3);
	});
	const onAppear16jj55a = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("SaB_4YMI7"), 2e3);
	});
	useOnVariantChange(baseVariant, {
		a8ROf930s: onAppear27vrgn,
		default: onAppear1tg5wz5,
		sz9N3g3MI: onAppearsy4wnq,
		Vg2pKRqL3: onAppear11o3rjk,
		yA6K4aJk6: onAppear16jj55a,
	});
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "a8ROf930s") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "sz9N3g3MI") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (
			["sz9N3g3MI", "a8ROf930s", "Vg2pKRqL3", "yA6K4aJk6"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed3 = () => {
		if (baseVariant === "Vg2pKRqL3") return true;
		return false;
	};
	const isDisplayed4 = () => {
		if (baseVariant === "yA6K4aJk6") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-3xk79r",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"SaB_4YMI7"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								a8ROf930s: {
									"data-framer-name": "Variant 3",
									background: {
										alt: "",
										positionX: "center",
										positionY: "center",
									},
								},
								sz9N3g3MI: {
									"data-framer-name": "Variant 2",
									background: {
										alt: "",
										positionX: "center",
										positionY: "center",
									},
								},
								Vg2pKRqL3: {
									"data-framer-name": "Variant 4",
									background: {
										alt: "",
										positionX: "center",
										positionY: "center",
									},
								},
								yA6K4aJk6: {
									"data-framer-name": "Variant 5",
									background: {
										alt: "",
										positionX: "center",
										positionY: "center",
									},
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 600,
									pixelWidth: 600,
									src: "https://framerusercontent.com/images/sOByZuE8rzv585dBkDeRRD3VrjU.png",
									srcSet:
										"https://framerusercontent.com/images/sOByZuE8rzv585dBkDeRRD3VrjU.png?scale-down-to=512 512w,https://framerusercontent.com/images/sOByZuE8rzv585dBkDeRRD3VrjU.png 600w",
								}}
								className={"framer-1dvh7lk"}
								layoutDependency={layoutDependency}
								layoutId={"KERA9nm0p"}
								{...addPropertyOverrides(
									{
										a8ROf930s: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.y) || 0) +
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.height) || 160) -
														166.5,
												),
												pixelHeight: 982,
												pixelWidth: 947,
												sizes:
													(componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.width) || "100vw",
												src: "https://framerusercontent.com/images/nObtdjVkEGRQitxzJa2fAiiQWG4.png",
												srcSet:
													"https://framerusercontent.com/images/nObtdjVkEGRQitxzJa2fAiiQWG4.png 947w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						{isDisplayed1() && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 600,
									pixelWidth: 600,
									src: "https://framerusercontent.com/images/sOByZuE8rzv585dBkDeRRD3VrjU.png",
									srcSet:
										"https://framerusercontent.com/images/sOByZuE8rzv585dBkDeRRD3VrjU.png?scale-down-to=512 512w,https://framerusercontent.com/images/sOByZuE8rzv585dBkDeRRD3VrjU.png 600w",
								}}
								className={"framer-ptwfmp"}
								layoutDependency={layoutDependency}
								layoutId={"RKbp8mhjT"}
								{...addPropertyOverrides(
									{
										sz9N3g3MI: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.y) || 0) +
														0 +
														((((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.height) || 160) -
															0 -
															215.5) /
															2 +
															0 +
															0),
												),
												pixelHeight: 600,
												pixelWidth: 600,
												sizes:
													(componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.width) || "100vw",
												src: "https://framerusercontent.com/images/sOByZuE8rzv585dBkDeRRD3VrjU.png",
												srcSet:
													"https://framerusercontent.com/images/sOByZuE8rzv585dBkDeRRD3VrjU.png?scale-down-to=512 512w,https://framerusercontent.com/images/sOByZuE8rzv585dBkDeRRD3VrjU.png 600w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						{isDisplayed2() && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 295,
									intrinsicWidth: 300,
									loading: getLoadingLazyAtYPosition(
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) +
											(((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.height) || 160) *
												0.4983922829581996 -
												125.5),
									),
									pixelHeight: 590,
									pixelWidth: 600,
									sizes:
										(componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.width) || "100vw",
									src: "https://framerusercontent.com/images/nVfg0wCczUhY25El2mKQ089ml4.png?scale-down-to=512",
									srcSet:
										"https://framerusercontent.com/images/nVfg0wCczUhY25El2mKQ089ml4.png?scale-down-to=512 512w,https://framerusercontent.com/images/nVfg0wCczUhY25El2mKQ089ml4.png 600w",
								}}
								className={"framer-1ivdczr"}
								data-framer-name={"Surface 1"}
								layoutDependency={layoutDependency}
								layoutId={"AnslL5Arr"}
								transformTemplate={transformTemplate1}
							/>
						)}
						{isDisplayed3() && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 3024,
									pixelWidth: 4032,
									src: "https://framerusercontent.com/images/7kh9I7Oz2smXPOduG5kIrQez9Jo.jpg",
									srcSet:
										"https://framerusercontent.com/images/7kh9I7Oz2smXPOduG5kIrQez9Jo.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/7kh9I7Oz2smXPOduG5kIrQez9Jo.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/7kh9I7Oz2smXPOduG5kIrQez9Jo.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/7kh9I7Oz2smXPOduG5kIrQez9Jo.jpg 4032w",
								}}
								className={"framer-13v85md"}
								layoutDependency={layoutDependency}
								layoutId={"sR8OCMEEw"}
								{...addPropertyOverrides(
									{
										Vg2pKRqL3: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.y) || 0) +
														(((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.height) || 160) *
															0.5000000000000002 -
															78),
												),
												pixelHeight: 3024,
												pixelWidth: 4032,
												sizes: `calc(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} * 0.88)`,
												src: "https://framerusercontent.com/images/7kh9I7Oz2smXPOduG5kIrQez9Jo.jpg",
												srcSet:
													"https://framerusercontent.com/images/7kh9I7Oz2smXPOduG5kIrQez9Jo.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/7kh9I7Oz2smXPOduG5kIrQez9Jo.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/7kh9I7Oz2smXPOduG5kIrQez9Jo.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/7kh9I7Oz2smXPOduG5kIrQez9Jo.jpg 4032w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						{isDisplayed4() && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 1512,
									intrinsicWidth: 2016,
									pixelHeight: 3024,
									pixelWidth: 4032,
									src: "https://framerusercontent.com/images/pYGWMum5kjSZ8FaqC6x6Zq3c5OQ.jpg?scale-down-to=2048",
									srcSet:
										"https://framerusercontent.com/images/pYGWMum5kjSZ8FaqC6x6Zq3c5OQ.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/pYGWMum5kjSZ8FaqC6x6Zq3c5OQ.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/pYGWMum5kjSZ8FaqC6x6Zq3c5OQ.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/pYGWMum5kjSZ8FaqC6x6Zq3c5OQ.jpg 4032w",
								}}
								className={"framer-i9ao0u"}
								data-framer-name={"IMG 8934"}
								layoutDependency={layoutDependency}
								layoutId={"tAisFvXD1"}
								{...addPropertyOverrides(
									{
										yA6K4aJk6: {
											background: {
												alt: "",
												fit: "fill",
												intrinsicHeight: 1512,
												intrinsicWidth: 2016,
												loading: getLoadingLazyAtYPosition(
													((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.y) || 0) +
														(((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.height) || 160) *
															0.5000000000000002 -
															((((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.height) || 160) -
																0) *
																0.9375) /
																2),
												),
												pixelHeight: 3024,
												pixelWidth: 4032,
												sizes: `calc(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} * 0.8813)`,
												src: "https://framerusercontent.com/images/pYGWMum5kjSZ8FaqC6x6Zq3c5OQ.jpg?scale-down-to=2048",
												srcSet:
													"https://framerusercontent.com/images/pYGWMum5kjSZ8FaqC6x6Zq3c5OQ.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/pYGWMum5kjSZ8FaqC6x6Zq3c5OQ.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/pYGWMum5kjSZ8FaqC6x6Zq3c5OQ.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/pYGWMum5kjSZ8FaqC6x6Zq3c5OQ.jpg 4032w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Rn9Mn.framer-1acc6ay, .framer-Rn9Mn .framer-1acc6ay { display: block; }",
	".framer-Rn9Mn.framer-3xk79r { height: 160px; overflow: hidden; position: relative; width: 160px; }",
	".framer-Rn9Mn .framer-1dvh7lk { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }",
	".framer-Rn9Mn .framer-ptwfmp { aspect-ratio: 0.7474402730375427 / 1; bottom: -30px; flex: none; height: var(--framer-aspect-ratio-supported, 268px); overflow: hidden; position: absolute; right: 0px; width: 1fr; }",
	".framer-Rn9Mn .framer-1ivdczr { aspect-ratio: 1.0169491525423728 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 158px); left: 0px; overflow: visible; position: absolute; top: 50%; width: 100%; }",
	".framer-Rn9Mn .framer-13v85md { flex: none; height: 156px; left: calc(50.00000000000002% - 88% / 2); position: absolute; top: calc(50.00000000000002% - 156px / 2); width: 88%; }",
	".framer-Rn9Mn .framer-i9ao0u { flex: none; height: 94%; left: calc(50.00000000000002% - 88.125% / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 93.75% / 2); width: 88%; }",
	".framer-Rn9Mn.framer-v-1is0smo.framer-3xk79r { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; justify-content: center; padding: 0px; }",
	".framer-Rn9Mn.framer-v-1is0smo .framer-ptwfmp { bottom: unset; height: var(--framer-aspect-ratio-supported, 214px); position: relative; right: unset; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Rn9Mn.framer-v-1is0smo.framer-3xk79r { gap: 0px; } .framer-Rn9Mn.framer-v-1is0smo.framer-3xk79r > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-Rn9Mn.framer-v-1is0smo.framer-3xk79r > :first-child { margin-top: 0px; } .framer-Rn9Mn.framer-v-1is0smo.framer-3xk79r > :last-child { margin-bottom: 0px; } }",
	".framer-Rn9Mn.framer-v-1fjkeyw .framer-1dvh7lk { aspect-ratio: 0.926829268292683 / 1; bottom: -6px; height: var(--framer-aspect-ratio-supported, 173px); right: unset; top: unset; width: 100%; }",
];
var Framerm9xBAxWo9 = withCSS(Component, css, "framer-Rn9Mn");
var stdin_default = Framerm9xBAxWo9;
Framerm9xBAxWo9.displayName = "X";
Framerm9xBAxWo9.defaultProps = {
	height: 160,
	width: 160,
};
addPropertyControls(Framerm9xBAxWo9, {
	variant: {
		options: ["SaB_4YMI7", "sz9N3g3MI", "a8ROf930s", "Vg2pKRqL3", "yA6K4aJk6"],
		optionTitles: [
			"Variant 1",
			"Variant 2",
			"Variant 3",
			"Variant 4",
			"Variant 5",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerm9xBAxWo9,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/0bhW0TTKh4XjSweuSYai/ICy36dBj8p2fR6nCVc7B/kR3Tje3H6.js
var XFonts = getFonts(stdin_default);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion2.div),
);
var serializationHash2 = "framer-dl4iP";
var variantClassNames2 = {
	V4aigIgLs: "framer-v-63ayfo",
};
var transition12 = {
	delay: 4.4,
	duration: 0.5,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition12,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate12 = (_, t) => `translateX(-50%) ${t}`;
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const { style, className, layoutId, variant, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "V4aigIgLs",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition2}>
					<MotionDivWithFXWithOptimizedAppearEffect
						{...restProps}
						{...gestureHandlers}
						__framer__presenceAnimate={animation}
						__framer__presenceInitial={animation1}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx2(
							scopingClassNames,
							"framer-63ayfo",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-appear-id={"63ayfo"}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"V4aigIgLs"}
						optimized={true}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-c46f0048-8063-4549-b986-a98eb786d799, rgb(222, 222, 222))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-79c2dc65-2d87-48f6-a074-bc219aa7f79f, rgb(245, 245, 245))",
							borderBottomLeftRadius: 12,
							borderBottomRightRadius: 12,
							borderTopLeftRadius: 12,
							borderTopRightRadius: 12,
							boxShadow:
								"0px 0.3613123810646357px 1.2284620956197614px -1px rgba(0, 0, 0, 0.07), 0px 1.3731199819460742px 4.668607938616653px -2px rgba(0, 0, 0, 0.07), 0px 6px 20.4px -3px rgba(0, 0, 0, 0.05)",
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-tcobty"}
							fonts={["CUSTOM;Helvetica Neue Regular"]}
							layoutDependency={layoutDependency}
							layoutId={"Td19wBa_w"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-1d772828-b6d9-4de2-8a9c-830291008724, rgb(153, 153, 153))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React2.Fragment>
								<motion2.p
									dir={"auto"}
									style={{
										"--font-selector":
											"Q1VTVE9NO0hlbHZldGljYSBOZXVlIFJlZ3VsYXI=",
										"--framer-font-family":
											'"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
										"--framer-font-size": "12px",
										"--framer-text-alignment": "left",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-1d772828-b6d9-4de2-8a9c-830291008724, rgb(153, 153, 153)))",
									}}
								>
									{"Moodboard"}
								</motion2.p>
							</React2.Fragment>
						</RichText>
						<motion2.div
							className={"framer-1joz764"}
							layoutDependency={layoutDependency}
							layoutId={"KRw2bGN81"}
							style={{
								opacity: 0.21,
							}}
						>
							<motion2.div
								className={"framer-1xqsz9"}
								layoutDependency={layoutDependency}
								layoutId={"VOqwr33pN"}
								style={{
									backgroundColor:
										"var(--token-d06fad13-dfbc-4d4f-9aac-f6d3359d35a0, rgb(85, 85, 85))",
								}}
							/>
							<motion2.div
								className={"framer-1llwptz"}
								layoutDependency={layoutDependency}
								layoutId={"nTGZOsBnW"}
							>
								<motion2.div
									className={"framer-xqdotr"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"xK_QkzSVw"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 999,
										borderBottomRightRadius: 999,
										borderTopLeftRadius: 999,
										borderTopRightRadius: 999,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-fgm9je"}
										fonts={["CUSTOM;Helvetica Neue Regular"]}
										layoutDependency={layoutDependency}
										layoutId={"jFCbIAX6w"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												dir={"auto"}
												style={{
													"--font-selector":
														"Q1VTVE9NO0hlbHZldGljYSBOZXVlIFJlZ3VsYXI=",
													"--framer-font-family":
														'"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
													"--framer-font-size": "10px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0)))",
												}}
											>
												{"User Experience"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
								<motion2.div
									className={"framer-jxuo90"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"OFYqVATgh"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 999,
										borderBottomRightRadius: 999,
										borderTopLeftRadius: 999,
										borderTopRightRadius: 999,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-14isnb3"}
										fonts={["CUSTOM;Helvetica Neue Regular"]}
										layoutDependency={layoutDependency}
										layoutId={"eYudI5DvM"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												dir={"auto"}
												style={{
													"--font-selector":
														"Q1VTVE9NO0hlbHZldGljYSBOZXVlIFJlZ3VsYXI=",
													"--framer-font-family":
														'"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
													"--framer-font-size": "10px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0)))",
												}}
											>
												{"UI"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
								<motion2.div
									className={"framer-76pi4l"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"NfVv7g_KQ"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 999,
										borderBottomRightRadius: 999,
										borderTopLeftRadius: 999,
										borderTopRightRadius: 999,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-vp4psn"}
										fonts={["CUSTOM;Helvetica Neue Regular"]}
										layoutDependency={layoutDependency}
										layoutId={"U1zB5eXVb"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												dir={"auto"}
												style={{
													"--font-selector":
														"Q1VTVE9NO0hlbHZldGljYSBOZXVlIFJlZ3VsYXI=",
													"--framer-font-family":
														'"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
													"--framer-font-size": "10px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0)))",
												}}
											>
												{"TUI"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
								<motion2.div
									className={"framer-14n83fi"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"umn8YuzXz"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 999,
										borderBottomRightRadius: 999,
										borderTopLeftRadius: 999,
										borderTopRightRadius: 999,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-gtl0wy"}
										fonts={["CUSTOM;Helvetica Neue Regular"]}
										layoutDependency={layoutDependency}
										layoutId={"QBcLerK8X"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												dir={"auto"}
												style={{
													"--font-selector":
														"Q1VTVE9NO0hlbHZldGljYSBOZXVlIFJlZ3VsYXI=",
													"--framer-font-family":
														'"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
													"--framer-font-size": "10px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0)))",
												}}
											>
												{"Speculative Design"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
								<motion2.div
									className={"framer-a4mgs7"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"Us3kvFFaR"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 999,
										borderBottomRightRadius: 999,
										borderTopLeftRadius: 999,
										borderTopRightRadius: 999,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-dw3s1q"}
										fonts={["CUSTOM;Helvetica Neue Regular"]}
										layoutDependency={layoutDependency}
										layoutId={"PHuswOmFO"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												dir={"auto"}
												style={{
													"--font-selector":
														"Q1VTVE9NO0hlbHZldGljYSBOZXVlIFJlZ3VsYXI=",
													"--framer-font-family":
														'"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
													"--framer-font-size": "10px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0)))",
												}}
											>
												{"Branding"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
								<motion2.div
									className={"framer-1gsj7px"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"Cz2ZgtokY"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 999,
										borderBottomRightRadius: 999,
										borderTopLeftRadius: 999,
										borderTopRightRadius: 999,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1orqjm5"}
										fonts={["CUSTOM;Helvetica Neue Regular"]}
										layoutDependency={layoutDependency}
										layoutId={"hxzXZT1ow"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												dir={"auto"}
												style={{
													"--font-selector":
														"Q1VTVE9NO0hlbHZldGljYSBOZXVlIFJlZ3VsYXI=",
													"--framer-font-family":
														'"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
													"--framer-font-size": "10px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0)))",
												}}
											>
												{"Product Manage"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
								<motion2.div
									className={"framer-1hd1nrc"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"YmCSxIAM8"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 999,
										borderBottomRightRadius: 999,
										borderTopLeftRadius: 999,
										borderTopRightRadius: 999,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1hpu2et"}
										fonts={["CUSTOM;Helvetica Neue Regular"]}
										layoutDependency={layoutDependency}
										layoutId={"ogT5m6Gqk"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												dir={"auto"}
												style={{
													"--font-selector":
														"Q1VTVE9NO0hlbHZldGljYSBOZXVlIFJlZ3VsYXI=",
													"--framer-font-family":
														'"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
													"--framer-font-size": "10px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0)))",
												}}
											>
												{"Web design"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
								<motion2.div
									className={"framer-2abx3g"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"VGUDTYVFU"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 999,
										borderBottomRightRadius: 999,
										borderTopLeftRadius: 999,
										borderTopRightRadius: 999,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-suqerx"}
										fonts={["CUSTOM;Helvetica Neue Regular"]}
										layoutDependency={layoutDependency}
										layoutId={"g1BnflDhk"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												dir={"auto"}
												style={{
													"--font-selector":
														"Q1VTVE9NO0hlbHZldGljYSBOZXVlIFJlZ3VsYXI=",
													"--framer-font-family":
														'"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
													"--framer-font-size": "10px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0)))",
												}}
											>
												{"Innotaive IxD method"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
							</motion2.div>
							<motion2.div
								className={"framer-aa3nl9"}
								layoutDependency={layoutDependency}
								layoutId={"k_Etyovbo"}
							/>
						</motion2.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-z8ld2y"}
							fonts={["CUSTOM;DT Random Display Regular"]}
							layoutDependency={layoutDependency}
							layoutId={"x4rCVkZjF"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51))",
								filter: "invert(0)",
								WebkitFilter: "invert(0)",
							}}
							transformTemplate={transformTemplate12}
							verticalAlignment={"top"}
							viewBox={"0 0 820.5 250"}
							withExternalLayout={true}
						>
							<React2.Fragment>
								<motion2.p
									dir={"auto"}
									style={{
										"--font-selector":
											"Q1VTVE9NO0RUIFJhbmRvbSBEaXNwbGF5IFJlZ3VsYXI=",
										"--framer-font-family":
											'"DT Random Display Regular", "DT Random Display Regular Placeholder", sans-serif',
										"--framer-font-size": "209.03641846814696px",
										"--framer-letter-spacing": "-0.07px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51)))",
									}}
								>
									{"yixiang"}
								</motion2.p>
							</React2.Fragment>
						</RichText>
						<motion2.div
							className={"framer-1rycgqq"}
							layoutDependency={layoutDependency}
							layoutId={"NkqJl2lQN"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-esphlr"}
								fonts={["CUSTOM;Helvetica Neue Medium"]}
								layoutDependency={layoutDependency}
								layoutId={"PFoTnyMs4"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-b176ef3c-b999-4cc9-84df-5c6564f91b31, rgb(221, 221, 221))",
									filter: "invert(0)",
									WebkitFilter: "invert(0)",
								}}
								verticalAlignment={"top"}
								viewBox={"0 0 819.07 3537"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										dir={"auto"}
										style={{
											"--font-selector":
												"Q1VTVE9NO0hlbHZldGljYSBOZXVlIE1lZGl1bQ==",
											"--framer-font-family":
												'"Helvetica Neue Medium", "Helvetica Neue Medium Placeholder", sans-serif',
											"--framer-font-size": "2947.8183988701367px",
											"--framer-font-weight": "500",
											"--framer-letter-spacing": "-0.07px",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-b176ef3c-b999-4cc9-84df-5c6564f91b31, rgb(221, 221, 221)))",
										}}
									>
										{"("}
									</motion2.p>
								</React2.Fragment>
							</RichText>
							<ComponentViewportProvider
								height={
									(((componentViewport?.height || 456) - 0) * 0.4178 - 0) * 1
								}
								width={
									(((componentViewport?.height || 456) - 0) * 0.4178 - 0) * 1
								}
								y={
									(componentViewport?.y || 0) +
									(componentViewport?.height || 456) -
									(48 + ((componentViewport?.height || 456) - 0) * 0.4178) +
									(0 +
										(((componentViewport?.height || 456) - 0) * 0.4178 -
											0 -
											(((componentViewport?.height || 456) - 0) * 0.4178 - 0) *
												1) /
											2)
								}
							>
								<SmartComponentScopedContainer
									className={"framer-70qoe0-container"}
									layoutDependency={layoutDependency}
									layoutId={"AfJVbIgpx-container"}
									nodeId={"AfJVbIgpx"}
									rendersWithMotion={true}
									scopeId={"kR3Tje3H6"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "AfJVbIgpx",
										layoutId: "AfJVbIgpx",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: matchVariant("SaB_4YMI7"),
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1d3w7jl"}
								fonts={["CUSTOM;Helvetica Neue Medium"]}
								layoutDependency={layoutDependency}
								layoutId={"ZOeM6QsQw"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-b176ef3c-b999-4cc9-84df-5c6564f91b31, rgb(221, 221, 221))",
									filter: "invert(0)",
									WebkitFilter: "invert(0)",
								}}
								verticalAlignment={"top"}
								viewBox={"0 0 32 137"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										dir={"auto"}
										style={{
											"--font-selector":
												"Q1VTVE9NO0hlbHZldGljYSBOZXVlIE1lZGl1bQ==",
											"--framer-font-family":
												'"Helvetica Neue Medium", "Helvetica Neue Medium Placeholder", sans-serif',
											"--framer-font-size": "114.41494056246196px",
											"--framer-font-weight": "500",
											"--framer-letter-spacing": "-0.07px",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-b176ef3c-b999-4cc9-84df-5c6564f91b31, rgb(221, 221, 221)))",
										}}
									>
										{")"}
									</motion2.p>
								</React2.Fragment>
							</RichText>
						</motion2.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-m7ur1f"}
							fonts={["CUSTOM;Helvetica Neue Medium"]}
							layoutDependency={layoutDependency}
							layoutId={"MTDnTcOHf"}
							style={{
								"--extracted-2gxw0f":
									"var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51))",
								"--extracted-r6o4lv":
									"var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51))",
								filter: "invert(0)",
								WebkitFilter: "invert(0)",
							}}
							verticalAlignment={"top"}
							viewBox={"0 0 97 17"}
							withExternalLayout={true}
						>
							<React2.Fragment>
								<motion2.p
									dir={"auto"}
									style={{
										"--font-selector":
											"Q1VTVE9NO0hlbHZldGljYSBOZXVlIE1lZGl1bQ==",
										"--framer-font-family":
											'"Helvetica Neue Medium", "Helvetica Neue Medium Placeholder", sans-serif',
										"--framer-font-size": "7.1636957128657714px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "-0.07px",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51)))",
									}}
								>
									{"Love crafting, "}
								</motion2.p>
								<motion2.p
									dir={"auto"}
									style={{
										"--font-selector":
											"Q1VTVE9NO0hlbHZldGljYSBOZXVlIE1lZGl1bQ==",
										"--framer-font-family":
											'"Helvetica Neue Medium", "Helvetica Neue Medium Placeholder", sans-serif',
										"--framer-font-size": "7.1636957128657714px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "-0.07px",
										"--framer-text-color":
											"var(--extracted-2gxw0f, var(--token-15299929-19cb-4d77-8337-32bb5aecdf45, rgb(51, 51, 51)))",
									}}
								>
									{"but crave creating even more."}
								</motion2.p>
							</React2.Fragment>
						</RichText>
					</MotionDivWithFXWithOptimizedAppearEffect>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-dl4iP.framer-xgb0b2, .framer-dl4iP .framer-xgb0b2 { display: block; }",
	".framer-dl4iP.framer-63ayfo { height: 456px; max-height: 500px; overflow: hidden; position: relative; width: 855px; will-change: var(--framer-will-change-override, transform); }",
	".framer-dl4iP .framer-tcobty { flex: none; height: auto; left: 16px; position: absolute; top: 12px; white-space: pre; width: auto; }",
	".framer-dl4iP .framer-1joz764 { align-content: flex-start; align-items: flex-start; bottom: 0px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: 44px; justify-content: flex-start; left: 0px; overflow: hidden; padding: 0px 16px 24px 16px; position: absolute; width: 100%; }",
	".framer-dl4iP .framer-1xqsz9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; overflow: hidden; padding: 0px 16px 0px 16px; position: relative; width: 100%; z-index: 1; }",
	".framer-dl4iP .framer-1llwptz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 18px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-dl4iP .framer-xqdotr, .framer-dl4iP .framer-jxuo90, .framer-dl4iP .framer-76pi4l, .framer-dl4iP .framer-14n83fi, .framer-dl4iP .framer-a4mgs7, .framer-dl4iP .framer-1gsj7px, .framer-dl4iP .framer-1hd1nrc, .framer-dl4iP .framer-2abx3g { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 4px 10px 2px 10px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-dl4iP .framer-fgm9je, .framer-dl4iP .framer-14isnb3, .framer-dl4iP .framer-vp4psn, .framer-dl4iP .framer-gtl0wy, .framer-dl4iP .framer-dw3s1q, .framer-dl4iP .framer-1orqjm5, .framer-dl4iP .framer-1hpu2et, .framer-dl4iP .framer-suqerx { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-dl4iP .framer-aa3nl9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; left: 0px; overflow: hidden; padding: 0px 16px 0px 16px; position: absolute; right: -412px; top: 0px; z-index: 1; }",
	".framer-dl4iP .framer-z8ld2y { flex: none; height: auto; left: 50%; position: absolute; top: -33px; white-space: pre; width: 96%; }",
	".framer-dl4iP .framer-1rycgqq { align-content: center; align-items: center; bottom: 48px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 42%; justify-content: center; overflow: hidden; padding: 0px; position: absolute; right: 20px; width: min-content; }",
	".framer-dl4iP .framer-esphlr, .framer-dl4iP .framer-1d3w7jl { flex: none; height: auto; position: relative; white-space: pre; width: 44px; }",
	".framer-dl4iP .framer-70qoe0-container { aspect-ratio: 1 / 1; flex: none; height: 100%; position: relative; width: var(--framer-aspect-ratio-supported, 191px); }",
	".framer-dl4iP .framer-m7ur1f { bottom: 68px; flex: none; height: auto; left: 16px; position: absolute; white-space: pre; width: 29%; }",
	'.framer-dl4iP[data-border="true"]::after, .framer-dl4iP [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerkR3Tje3H6 = withCSS2(Component2, css2, "framer-dl4iP");
var stdin_default2 = FramerkR3Tje3H6;
FramerkR3Tje3H6.displayName = "Name";
FramerkR3Tje3H6.defaultProps = {
	height: 456,
	width: 855,
};
addFonts2(
	FramerkR3Tje3H6,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Helvetica Neue Regular",
					source: "custom",
					style: "normal",
					uiFamilyName: "Helvetica Neue",
					url: "https://framerusercontent.com/assets/Jpz4cp1ymPZ257bFISNAe4E29U.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "DT Random Display Regular",
					source: "custom",
					style: "normal",
					uiFamilyName: "DT Random Display",
					url: "https://framerusercontent.com/assets/hK3sJzCK6ghCByBgWa8Pvo11w.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Helvetica Neue Medium",
					source: "custom",
					style: "normal",
					uiFamilyName: "Helvetica Neue",
					url: "https://framerusercontent.com/assets/jU9WF0d02oFMMgYZ1xKut1aiItI.woff2",
					weight: "500",
				},
			],
		},
		...XFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:name
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	BSdLfPlFv: {
		path: "/page-2",
	},
	EtSdg4Ryv: {
		path: "/gallery",
	},
	NyFQaT8qF: {
		path: "/collection",
	},
	SalSpG1qL: {
		path: "/me",
	},
	VF5TFFkxe: {
		path: "/page",
	},
	YsUGSl01d: {
		path: "/mel:mory-cube",
	},
	augiA20Il: {
		path: "/",
	},
	i8QcSamIG: {
		path: "/nrf",
	},
};

// virtual:name
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"65748388c4c5aa0511f0aa576eb2d1c5feadddaeed2a0d5791c0e9e8ce3a16dc"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NameFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"65748388c4c5aa0511f0aa576eb2d1c5feadddaeed2a0d5791c0e9e8ce3a16dc"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var name_default = ComponentWithRoot;
export { name_default as default };
