export const nameBoxClasses = {
  moodboardText: "moodboard-text max-[1200px]:!left-[8px] max-[1200px]:!top-[8px]",
  moodboardP: "max-[600px]:!text-[8px]",
  xIconContainer: "x-icon-container max-[480px]:!right-[12px]",
  xIconWrapper: "x-icon-wrapper max-[600px]:!w-[120px]"
};

export const nameBoxStyles = {
	box: {
		containerType: "inline-size",
		flex: "1 0 0px",
		height: "100%",
		overflow: "hidden",
		position: "relative",
		width: "100%",
		willChange: "var(--framer-will-change-override, transform)",
		border: "1px solid var(--color-border-default, rgb(219, 219, 219))",
		backgroundColor: "var(--color-bg-secondary, rgb(245, 245, 245))",
		borderRadius: 12,
		boxShadow:
			"0px 0.361312px 1.22846px -1px rgba(0, 0, 0, 0.07), 0px 1.37312px 4.66861px -2px rgba(0, 0, 0, 0.07), 0px 6px 20.4px -3px rgba(0, 0, 0, 0.05)",
	},
	moodboardText: {
		flex: "none",
		height: "auto",
		left: 16,
		position: "absolute",
		top: 12,
		whiteSpace: "pre",
		width: "auto",
		color: "var(--color-text-muted, rgb(153, 153, 153))",
	},
	moodboardP: {
		fontFamily:
			'"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
		fontSize: "12px",
		textAlign: "left",
		color: "var(--color-text-muted, rgb(153, 153, 153))",
		margin: 0,
	},
	bottomContainer: {
		alignContent: "flex-start",
		alignItems: "flex-start",
		bottom: 0,
		display: "flex",
		flex: "none",
		flexDirection: "column",
		flexWrap: "nowrap",
		gap: "clamp(4px, 1.2cqw, 12px)",
		height: "auto",
		justifyContent: "flex-start",
		left: 0,
		overflow: "hidden",
		padding: "0px clamp(8px, 1.6cqw, 24px) clamp(8px, 1.6cqw, 24px) clamp(8px, 1.6cqw, 24px)",
		position: "absolute",
		width: "100%",
		opacity: 0.21,
	},
	separator: {
		alignContent: "center",
		alignItems: "center",
		display: "flex",
		flex: "none",
		flexDirection: "row",
		flexWrap: "nowrap",
		gap: "1cqw",
		height: 1,
		justifyContent: "center",
		overflow: "hidden",
		padding: "0px 1.6cqw 0px 1.6cqw",
		position: "relative",
		width: "100%",
		zIndex: 1,
		backgroundColor: "var(--color-text-secondary, rgb(85, 85, 85))",
	},
	tagsContainer: {
		alignContent: "flex-start",
		alignItems: "center",
		display: "flex",
		flex: "none",
		flexDirection: "row",
		flexWrap: "wrap", // Restore wrap, it shouldn't wrap if perfectly scaled
		gap: "0.8cqw", // Pure cqw for perfect scaling
		height: "auto",
		overflow: "visible", 
		padding: 0,
		position: "relative",
		width: "100%",
	},
	tag: {
		alignContent: "center",
		alignItems: "center",
		display: "flex",
		flex: "none",
		flexDirection: "column",
		flexWrap: "nowrap",
		gap: "1cqw",
		height: "min-content",
		justifyContent: "center",
		overflow: "hidden",
		padding: "0.4cqw 1cqw 0.2cqw 1cqw", // Pure cqw for perfect scaling
		position: "relative",
		width: "auto",
		willChange: "var(--framer-will-change-override, transform)",
		border: "1px solid var(--color-text-primary, rgb(51, 51, 51))",
		borderRadius: 999,
	},
	tagTextWrapper: {
		color: "var(--color-text-inverse, rgb(0, 0, 0))",
	},
	tagP: {
		fontFamily:
			'"Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif',
		fontSize: "1.4cqw", // Pure cqw for true proportional scaling
		color: "var(--color-text-inverse, rgb(0, 0, 0))",
		margin: 0,
        whiteSpace: "nowrap",
	},
	spacer: {
		alignContent: "center",
		alignItems: "center",
		display: "flex",
		flex: "none",
		flexDirection: "row",
		flexWrap: "nowrap",
		gap: 10,
		height: 1,
		justifyContent: "center",
		left: 0,
		overflow: "hidden",
		padding: "0px 16px 0px 16px",
		position: "absolute",
		right: -412,
		top: 0,
		zIndex: 1,
	},
	yixiangText: {
		flex: "none",
		height: "auto",
		left: "50%",
		position: "absolute",
		top: 24,
		whiteSpace: "pre",
		width: "96%",
		color: "var(--color-text-primary, rgb(51, 51, 51))",
		filter: "invert(0)",
		WebkitFilter: "invert(0)",
		transform: "translateX(-50%)",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
	},
	svgText: {
		fontFamily:
			'"DT Random Display Regular", "DT Random Display Regular Placeholder", sans-serif',
		fontSize: "24px",
		letterSpacing: "-0.07px",
	},
	xIconContainer: {
		alignContent: "center",
		alignItems: "center",
		bottom: "clamp(12px, 6.8cqw, 60px)", // Reverted to cqw to match original design intent
		display: "flex",
		flex: "none",
		flexDirection: "row",
		flexWrap: "nowrap",
		gap: 0,
		height: "30%",
		justifyContent: "flex-end", // Align content to the right
		overflow: "visible",
		padding: 0,
		position: "absolute",
		right: 20, // Changed from 40 to 20
		width: "auto", // Changed from min-content
		zIndex: 10,
	},
	parenthesisText: {
		flex: "none",
		height: "100%",
		position: "relative",
		whiteSpace: "pre",
		width: 44,
		color: "var(--color-border-strong, rgb(221, 221, 221))",
		filter: "invert(0)",
		WebkitFilter: "invert(0)",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
	},
	parenthesisP: {
		fontFamily:
			'"Helvetica Neue Medium", "Helvetica Neue Medium Placeholder", sans-serif',
		fontSize: "80px",
		fontWeight: 500,
		letterSpacing: "-0.07px",
		color: "var(--color-border-strong, rgb(221, 221, 221))",
		margin: 0,
		lineHeight: 1,
	},
	rightParenthesisP: {
		fontFamily:
			'"Helvetica Neue Medium", "Helvetica Neue Medium Placeholder", sans-serif',
		fontSize: "80px", // Changed to match left parenthesis
		fontWeight: 500,
		letterSpacing: "-0.07px",
		color: "var(--color-border-strong, rgb(221, 221, 221))",
		margin: 0,
	},
	xIcon: {
		aspectRatio: "1 / 1",
		flex: "none",
		height: "100%",
		position: "relative",
		width: "var(--framer-aspect-ratio-supported, 191px)",
	},
	imageWrapper: {
		position: "relative",
		width: "100%",
		height: "100%",
	},
	image: {
		width: "100%",
		height: "100%",
		objectFit: "contain",
		display: "block",
		transition: "opacity 0.5s ease-in-out",
	},
	loveCraftingText: {
		bottom: "clamp(12px, 6.8cqw, 60px)",
		flex: "none",
		height: "auto",
		left: "1.6cqw",
		position: "absolute",
		whiteSpace: "pre",
		width: "30%",
		color: "var(--color-text-primary, rgb(51, 51, 51))",
		filter: "invert(0)",
		WebkitFilter: "invert(0)",
	},
	loveCraftingP: {
		fontFamily:
			'"Helvetica Neue Medium", "Helvetica Neue Medium Placeholder", sans-serif',
		fontSize: "clamp(12px, 2.2cqw, 24px)",
		fontWeight: 500,
		letterSpacing: "-0.07px",
		color: "var(--color-text-primary, rgb(51, 51, 51))",
		margin: 0,
	},
} as const;
