import { CSSProperties } from "react";

export const projectGridStyles = {
  section: {
    position: "relative",
    width: "100%",
    backgroundColor: "var(--color-bg-page, #ffffff)",
    minHeight: "100vh",
    paddingLeft: "8px",
    paddingRight: "8px",
    paddingTop: "8px",
    paddingBottom: "8px",
    overflowX: "clip",
  } as CSSProperties,
  stickyContainer: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
  } as CSSProperties,
  header: {
    display: "flex",
    width: "calc(100% + 16px)",
    marginLeft: "-8px",
    marginRight: "-8px",
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingLeft: "8px",
    paddingRight: "8px",
    paddingTop: "8px",
    paddingBottom: "8px",
    flex: "none",
    position: "sticky",
    top: 0,
    zIndex: 100,
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
  } as CSSProperties,
  title: {
    fontSize: "90px",
    lineHeight: 1,
    letterSpacing: "-0.025em",
    color: "var(--color-text-primary)",
    fontFamily: "TikTok Sans, Inter, sans-serif",
    fontWeight: 400,
    margin: 0,
    width: "60%",
  } as CSSProperties,
  metaContainer: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    width: "40%",
  } as CSSProperties,
  tabsContainer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  } as CSSProperties,
  tabItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    padding: "8px 12px",
    borderRadius: "999px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxSizing: "border-box",
  } as CSSProperties,
  tabText: {
    fontFamily: "TikTok Sans, Inter, sans-serif",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: 1.12,
  } as CSSProperties,
  tabCount: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "16px",
    height: "16px",
    borderRadius: "999px",
    fontFamily: "TikTok Sans, Inter, sans-serif",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: 1,
  } as CSSProperties,
  scrollContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    alignItems: "center",
    overflow: "visible",
    width: "100%",
    marginTop: "24px",
    marginBottom: "60px",
  } as CSSProperties,
  motionContainer: {
    display: "flex",
    flexDirection: "row",
    gap: "8px",
    width: "100%",
    paddingLeft: "0px",
    paddingRight: "0px",
  } as CSSProperties,
  gridColumn: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    minWidth: 0,
  } as CSSProperties,
  bigCard: {
    flex: 2,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    minWidth: 0,
    position: "relative",
  } as CSSProperties,
  tallCard: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    minWidth: 0,
    position: "relative",
  } as CSSProperties,
  card: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    position: "relative",
  } as CSSProperties,
  cursorTagContainer: {
    position: "fixed",
    pointerEvents: "none",
    zIndex: 10000,
    display: "flex",
    gap: "4px",
  } as CSSProperties,
  cursorTag: {
    padding: "6px 12px",
    backgroundColor: "#FFFFFF",
    color: "#000000",
    borderRadius: "999px",
    fontSize: "12px",
    fontWeight: 500,
    whiteSpace: "nowrap",
    fontFamily: "TikTok Sans, Inter, sans-serif",
  } as CSSProperties,
  shimmerWrapper: {
    position: "absolute",
    inset: "-1px",
    borderRadius: "13px",
    padding: "1px",
    zIndex: 10,
    opacity: 0,
    transition: "opacity 0.3s ease",
    pointerEvents: "none",
    WebkitMask: "linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)",
    WebkitMaskComposite: "xor",
    mask: "linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)",
    maskComposite: "exclude",
  } as CSSProperties,
  shimmerGlow: {
    position: "absolute",
    inset: "-15px",
    borderRadius: "27px",
    zIndex: -1,
    opacity: 0,
    transition: "opacity 0.5s ease",
    pointerEvents: "none",
    filter: "blur(10px)",
  } as CSSProperties,
  cardCover: {
    width: "100%",
    aspectRatio: "16 / 10",
    backgroundColor: "var(--color-bg-tertiary)",
    borderRadius: "12px",
    border: "1px solid var(--color-border-strong, rgb(221, 221, 221))",
    overflow: "hidden",
    boxSizing: "border-box",
  } as CSSProperties,
  cardInfo: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "8px",
    padding: "0 4px",
  } as CSSProperties,
  cardTitle: {
    fontSize: "16px",
    fontWeight: 500,
    color: "var(--color-text-primary)",
    fontFamily: "TikTok Sans, Inter, sans-serif",
    lineHeight: 1.2,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    flexShrink: 0,
  } as CSSProperties,
  cardMeta: {
    fontSize: "12px",
    color: "var(--color-text-muted)",
    fontFamily: "TikTok Sans, Inter, sans-serif",
    lineHeight: 1.2,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    textAlign: "right",
    marginLeft: "0px",
    flex: 1,
    minWidth: 0,
  } as CSSProperties,
};
