// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e0afd6ff418761bc "Portfolio (copy)", do not edit manually */
"use client";

// virtual:bracelet
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8L50xdSy5ObbzajhoHKs/YTS0QhUusyLwDoFw6IJ4/dZWCEo14J.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/I1DC9cTt2FcHsDUAaRxW/OobIpExjjda7YDjHO9YN/SVG.js
import { jsx as _jsx } from "react/jsx-runtime";
import { useState, useEffect } from "react";
import { addPropertyControls, ControlType } from "unframer";
function SVG(props) {
	const [customSvgElement, setCustomSvgElement] = useState(null);
	useEffect(() => {
		const svgContent = props.customSvgCode;
		processCustomSVGContent(svgContent);
	});
	const processCustomSVGContent = (svgContent) => {
		const replacements = [
			[/width="[^"]*"/, 'width="100%"'],
			[/height="[^"]*"/, 'height="100%"'],
		];
		const hasCustomStroke = svgContent.includes('stroke="');
		const hasCustomStrokeWidth = svgContent.includes('stroke-width="');
		const hasLineCap = svgContent.includes('stroke-linecap="');
		const hasLineJoin = svgContent.includes('stroke-linejoin="');
		if (svgContent.includes("<circle")) {
			const circleFillRegex = /<circle[^>]*fill="([^"]*)"/;
			const match = svgContent.match(circleFillRegex);
			if (match) {
				const updatedCircle = match[0].replace(match[1], props.customColor);
				svgContent = svgContent.replace(circleFillRegex, updatedCircle);
			} else {
				replacements.push([/<circle/g, `<circle fill="${props.customColor}"`]);
			}
		}
		if (hasCustomStroke) {
			if (!hasLineCap) {
				replacements.push([/<path/g, `<path stroke="${props.customColor}"`]);
			} else {
				replacements.push([
					/<path/g,
					`<path stroke="${props.customColor}" stroke-linecap="${props.lineCap}"`,
				]);
			}
			if (hasCustomStrokeWidth) {
				replacements.push([
					/stroke-width="(?!0\b)\d+(\.\d+)?"/g,
					`stroke-width="${props.customStrokeWidth}"`,
				]);
			}
		} else {
			replacements.push([/<path/g, `<path fill="${props.customColor}"`]);
		}
		if (svgContent.includes('overflow="')) {
			replacements.push([/overflow="[^"]*"/, `overflow="visible"`]);
		} else {
			replacements.push([/<svg/, `<svg overflow="visible"`]);
		}
		if (!hasLineJoin) {
			replacements.push([
				/<path/g,
				`<path stroke-linejoin="${props.lineJoin}"`,
			]);
		} else {
			replacements.push([
				/stroke-linejoin="[^"]*"/,
				`stroke-linejoin="${props.lineJoin}"`,
			]);
		}
		replacements.forEach(([regex, replacement]) => {
			svgContent = svgContent.replace(regex, replacement);
		});
		setCustomSvgElement(svgContent);
	};
	const customContainerStyle = {
		padding: `${props.customPadding}px`,
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		overflow: "visible",
	};
	return (
		<div
			dangerouslySetInnerHTML={{
				__html: customSvgElement,
			}}
			style={customContainerStyle}
		/>
	);
}
SVG.defaultProps = {
	customSvgCode: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_967_124)"> <path d="M18 6.09674C18 6.0348 18.0246 5.97539 18.0684 5.93159L23.6013 0.398708C23.7484 0.251575 24 0.35578 24 0.563858V11.9033C24 11.9652 23.9754 12.0246 23.9316 12.0684L18 18V6.09674Z" fill="white"/> <path d="M6 18V6.56386C6 6.35578 5.74843 6.25158 5.60129 6.39871L0.0684074 11.9316C0.0246069 11.9754 0 12.0348 0 12.0967V23.7664C0 23.8954 0.104567 24 0.233557 24H11.9033C11.9652 24 12.0246 23.9754 12.0684 23.9316L18 18H6Z" fill="white"/> </g> <defs> <clipPath id="clip0_967_124"> <rect width="24" height="24" fill="white"/> </clipPath> </defs> </svg>`,
	customColor: "#ffffff",
	customPadding: 0,
	customStrokeWidth: 2,
	lineCap: "butt",
	lineJoin: "miter",
};
addPropertyControls(SVG, {
	customSvgCode: {
		type: ControlType.String,
		title: "SVG Code",
		displayTextArea: false,
	},
	customColor: {
		type: ControlType.Color,
		title: "Color",
		defaultValue: "#ffffff",
	},
	customPadding: {
		type: ControlType.Number,
		title: "Padding",
		defaultValue: 0,
		min: 0,
		step: 1,
		displayStepper: true,
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
	},
	customStrokeWidth: {
		type: ControlType.Number,
		title: "Stroke",
		defaultValue: 2,
		min: 0,
		step: 0.1,
		displayStepper: true,
		hidden: (props) => !props.customSvgCode.includes('stroke="'),
	},
	lineCap: {
		type: ControlType.Enum,
		title: "Line Cap",
		options: ["butt", "round", "square"],
		optionTitles: ["Butt", "Round", "Square"],
		defaultValue: "butt",
		hidden: (props) => !props.customSvgCode.includes('stroke="'),
	},
	lineJoin: {
		type: ControlType.Enum,
		title: "Line Join",
		options: ["round", "miter", "bevel"],
		optionTitles: ["Round", "Miter", "Bevel"],
		defaultValue: "miter",
		hidden: (props) => !props.customSvgCode.includes('stroke="'),
	},
});
var stdin_default = SVG;

// /:https://framerusercontent.com/modules/iBn52q0nRdvsUODQTruZ/Klbp8Z5SSB6WbbSgfazB/CcwSqYSHZ.js
import { fontStore } from "unframer";
fontStore.loadFonts(["CUSTOM;Helvetica Neue Regular"]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Helvetica Neue Regular",
				source: "custom",
				url: "https://framerusercontent.com/assets/Jpz4cp1ymPZ257bFISNAe4E29U.woff2",
			},
		],
	},
];
var css = [
	'.framer-4Fwpf .framer-styles-preset-1nr15yr:not(.rich-text-wrapper), .framer-4Fwpf .framer-styles-preset-1nr15yr.rich-text-wrapper h1 { --framer-font-family: "Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: left; --framer-text-color: var(--token-1d772828-b6d9-4de2-8a9c-830291008724, #999999); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1599px) and (min-width: 810px) { .framer-4Fwpf .framer-styles-preset-1nr15yr:not(.rich-text-wrapper), .framer-4Fwpf .framer-styles-preset-1nr15yr.rich-text-wrapper h1 { --framer-font-family: "Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: left; --framer-text-color: var(--token-1d772828-b6d9-4de2-8a9c-830291008724, #999999); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-4Fwpf .framer-styles-preset-1nr15yr:not(.rich-text-wrapper), .framer-4Fwpf .framer-styles-preset-1nr15yr.rich-text-wrapper h1 { --framer-font-family: "Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: left; --framer-text-color: var(--token-1d772828-b6d9-4de2-8a9c-830291008724, #999999); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className = "framer-4Fwpf";

// /:https://framerusercontent.com/modules/haIm7rkwqJ16qyN6RkdS/zWtWcbi8340d89mqRLXz/K6_8GDja6.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts(["CUSTOM;Helvetica Neue Regular"]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Helvetica Neue Regular",
				source: "custom",
				url: "https://framerusercontent.com/assets/Jpz4cp1ymPZ257bFISNAe4E29U.woff2",
			},
		],
	},
];
var css2 = [
	'.framer-9VhVd .framer-styles-preset-1g780v8:not(.rich-text-wrapper), .framer-9VhVd .framer-styles-preset-1g780v8.rich-text-wrapper h4 { --framer-font-family: "Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: left; --framer-text-color: var(--token-dbf0a442-1faf-4812-92a1-be0c74219dab, #bbbbbb); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-9VhVd .framer-styles-preset-1g780v8:not(.rich-text-wrapper), .framer-9VhVd .framer-styles-preset-1g780v8.rich-text-wrapper h4 { --framer-font-family: "Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 10px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: left; --framer-text-color: var(--token-dbf0a442-1faf-4812-92a1-be0c74219dab, #bbbbbb); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-9VhVd .framer-styles-preset-1g780v8:not(.rich-text-wrapper), .framer-9VhVd .framer-styles-preset-1g780v8.rich-text-wrapper h4 { --framer-font-family: "Helvetica Neue Regular", "Helvetica Neue Regular Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 8px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: left; --framer-text-color: var(--token-dbf0a442-1faf-4812-92a1-be0c74219dab, #bbbbbb); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-9VhVd";

// /:https://framerusercontent.com/modules/8L50xdSy5ObbzajhoHKs/YTS0QhUusyLwDoFw6IJ4/dZWCEo14J.js
var SVGFonts = getFonts(stdin_default);
var serializationHash = "framer-zmKH7";
var variantClassNames = {
	ZFpgQWTyF: "framer-v-1rrxbaa",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "ZFpgQWTyF",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1rrxbaa",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"ZFpgQWTyF"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-146n8y5"}
							layoutDependency={layoutDependency}
							layoutId={"gaqtgV9WH"}
						>
							<motion.div
								className={"framer-1h3npoi"}
								layoutDependency={layoutDependency}
								layoutId={"XbQONcOFB"}
								style={{
									backgroundColor:
										"var(--token-d06fad13-dfbc-4d4f-9aac-f6d3359d35a0, rgb(85, 85, 85))",
									borderBottomLeftRadius: 300,
									borderBottomRightRadius: 300,
									borderTopLeftRadius: 300,
									borderTopRightRadius: 300,
								}}
							>
								<motion.div
									className={"framer-5laipa"}
									layoutDependency={layoutDependency}
									layoutId={"tUB4vfRN5"}
									style={{
										backgroundColor:
											"var(--token-79c2dc65-2d87-48f6-a074-bc219aa7f79f, rgb(245, 245, 245))",
									}}
								>
									<Image
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													0 +
													0 +
													((((componentViewport?.height || 506.5) - 0) * 1 -
														0 -
														(Math.max(
															0,
															(((componentViewport?.height || 506.5) - 0) * 1 -
																0 -
																36.4) /
																1,
														) *
															1 +
															26.4 +
															10)) /
														2 +
														0 +
														0) +
													0 +
													((Math.max(
														0,
														(((componentViewport?.height || 506.5) - 0) * 1 -
															0 -
															36.4) /
															1,
													) *
														1 -
														0) *
														1 *
														0.4992076069730589 -
														(((Math.max(
															0,
															(((componentViewport?.height || 506.5) - 0) * 1 -
																0 -
																36.4) /
																1,
														) *
															1 -
															0) *
															1 -
															0) *
															1) /
															2),
											),
											pixelHeight: 1080,
											pixelWidth: 1920,
											positionX: "center",
											positionY: "center",
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/cO979P57CmDgOVka7aJmnHZ2U.jpg?width=1920&height=1080",
											srcSet:
												"https://framerusercontent.com/images/cO979P57CmDgOVka7aJmnHZ2U.jpg?scale-down-to=512&width=1920&height=1080 512w,https://framerusercontent.com/images/cO979P57CmDgOVka7aJmnHZ2U.jpg?scale-down-to=1024&width=1920&height=1080 1024w,https://framerusercontent.com/images/cO979P57CmDgOVka7aJmnHZ2U.jpg?width=1920&height=1080 1920w",
										}}
										className={"framer-c7hmys"}
										layoutDependency={layoutDependency}
										layoutId={"O9UILtNjO"}
									/>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-6g6dg0-container"}
											data-framer-name={"Moon"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"FQWLiHBE6-container"}
											name={"Moon"}
											nodeId={"FQWLiHBE6"}
											rendersWithMotion={true}
											scopeId={"dZWCEo14J"}
											transformTemplate={transformTemplate1}
										>
											{_jsx2(stdin_default, {
												customColor:
													"var(--token-696a8252-c3f9-4cbc-ae7c-d77ee3389d07, rgb(255, 255, 255))",
												customPadding: 0,
												customStrokeWidth: 2,
												customSvgCode:
													'<svg width="592" height="202" viewBox="0 0 592 202" fill="none" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" clip-rule="evenodd" d="M7.10759 202C80.0633 202 135.178 138.836 173.518 76.7668C202.438 29.949 246.732 0 296.383 0C346.148 0 390.532 30.087 419.447 77.0902C457.563 139.05 512.533 202 585.278 202C587.532 202 589.773 201.944 592 201.833V202H585.278H7.10759ZM0 201.814V202H7.10759C4.72327 202 2.35356 201.937 0 201.814Z" fill="#D9D9D9"/> </svg>',
												height: "100%",
												id: "FQWLiHBE6",
												layoutId: "FQWLiHBE6",
												lineCap: "butt",
												lineJoin: "miter",
												name: "Moon",
												style: {
													height: "100%",
													width: "100%",
												},
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<motion.div
										className={"framer-fkzxa8"}
										layoutDependency={layoutDependency}
										layoutId={"Jk5zmkdAH"}
										style={{
											backgroundColor:
												"var(--token-a07a24bb-b859-428e-924f-c4184b08086b, rgb(0, 0, 0))",
											borderBottomLeftRadius: 999,
											borderBottomRightRadius: 999,
											borderTopLeftRadius: 999,
											borderTopRightRadius: 999,
										}}
										transformTemplate={transformTemplate1}
									>
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-sa0g64-container"}
												data-framer-name={"Moon"}
												isAuthoredByUser={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"nbKGY0lom-container"}
												name={"Moon"}
												nodeId={"nbKGY0lom"}
												rendersWithMotion={true}
												scopeId={"dZWCEo14J"}
												transformTemplate={transformTemplate2}
											>
												{_jsx2(stdin_default, {
													customColor:
														"var(--token-b176ef3c-b999-4cc9-84df-5c6564f91b31, rgb(221, 221, 221))",
													customPadding: 0,
													customStrokeWidth: 2,
													customSvgCode:
														'<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M43.4142 22.5858L28.1213 7.29289C27.7308 6.90237 27.0976 6.90237 26.7071 7.29289L25.2929 8.70711C24.9024 9.09763 24.9024 9.7308 25.2929 10.1213L37.1716 22H5C4.44772 22 4 22.4477 4 23V25C4 25.5523 4.44771 26 5 26H37.1716L25.2929 37.8787C24.9024 38.2692 24.9024 38.9024 25.2929 39.2929L26.7071 40.7071C27.0976 41.0976 27.7308 41.0976 28.1213 40.7071L43.4142 25.4142C44.1953 24.6332 44.1953 23.3668 43.4142 22.5858Z" fill="black"/> </svg>',
													height: "100%",
													id: "nbKGY0lom",
													layoutId: "nbKGY0lom",
													lineCap: "butt",
													lineJoin: "miter",
													name: "Moon",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion.div>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-65l5o8"}
								layoutDependency={layoutDependency}
								layoutId={"n9M0s35q4"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-zokx0m"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"wwuuSW63e"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h1
											className={"framer-styles-preset-1nr15yr"}
											data-styles-preset={"CcwSqYSHZ"}
											dir={"auto"}
										>
											{"Embracelet"}
										</motion.h1>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1gkyfpv"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"oU7OEkOCM"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-1g780v8"}
											data-styles-preset={"K6_8GDja6"}
											dir={"auto"}
										>
											{"UI / UX research / Innovative / 3D"}
										</motion.h4>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-zmKH7.framer-19rzw37, .framer-zmKH7 .framer-19rzw37 { display: block; }",
	".framer-zmKH7.framer-1rrxbaa { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: 507px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 800px; }",
	".framer-zmKH7 .framer-146n8y5 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-zmKH7 .framer-1h3npoi { flex: 1 0 0px; height: 1px; overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-zmKH7 .framer-5laipa { -webkit-user-select: none; flex: none; height: 100%; left: 0px; overflow: hidden; position: absolute; top: 0px; user-select: none; width: 100%; }",
	".framer-zmKH7 .framer-c7hmys { flex: none; height: 100%; left: calc(49.946409431940005% - 100% / 2); overflow: visible; position: absolute; top: calc(49.92076069730589% - 100% / 2); width: 100%; }",
	".framer-zmKH7 .framer-6g6dg0-container { aspect-ratio: 2.888888888888889 / 1; bottom: -1px; flex: none; height: var(--framer-aspect-ratio-supported, 55px); left: 50%; position: absolute; width: 20%; }",
	".framer-zmKH7 .framer-fkzxa8 { aspect-ratio: 1 / 1; bottom: 0px; flex: none; height: var(--framer-aspect-ratio-supported, 46px); left: 50%; overflow: hidden; position: absolute; width: 6%; will-change: var(--framer-will-change-override, transform); }",
	".framer-zmKH7 .framer-sa0g64-container { aspect-ratio: 1.25 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 23px); left: 50%; position: absolute; top: 50%; width: 50%; }",
	".framer-zmKH7 .framer-65l5o8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-zmKH7 .framer-zokx0m, .framer-zmKH7 .framer-1gkyfpv { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
	...css2,
];
var FramerdZWCEo14J = withCSS(Component, css3, "framer-zmKH7");
var stdin_default2 = FramerdZWCEo14J;
FramerdZWCEo14J.displayName = "bracelet";
FramerdZWCEo14J.defaultProps = {
	height: 506.5,
	width: 800,
};
addFonts(
	FramerdZWCEo14J,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SVGFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:bracelet
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	BSdLfPlFv: {
		path: "/page-2",
	},
	EtSdg4Ryv: {
		path: "/gallery",
	},
	NyFQaT8qF: {
		path: "/collection",
	},
	SalSpG1qL: {
		path: "/me",
	},
	VF5TFFkxe: {
		path: "/page",
	},
	YsUGSl01d: {
		path: "/mel:mory-cube",
	},
	augiA20Il: {
		path: "/",
	},
	i8QcSamIG: {
		path: "/nrf",
	},
};

// virtual:bracelet
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e0afd6ff418761bc358d4cbfcb8628895c9e629b7235554d7162d447622dc1d3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BraceletFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e0afd6ff418761bc358d4cbfcb8628895c9e629b7235554d7162d447622dc1d3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var bracelet_default = ComponentWithRoot;
export { bracelet_default as default };
